testTech/testTech/urls.py
from django.contrib import admin
from django.urls import include, path

# Two patterns : the worldMap to access to the app.
#                the admin which is not use
urlpatterns = [
    path('worldMap/', include('worldMap.urls')),
    # path('admin/', admin.site.urls),
]

testTech/worldMap/urls.py
from django.urls import path, include

from . import views


app_name = 'worldMap'

# Url Patterns for the worldMap App

urlpatterns = [
    path('', views.home, name='home'),
    path('api/', views.getJson, name='api'),
]

testTech/worldMap/models.py
from django.db import models
from django.db.models import Model

# The model for the gps coordinates.

class Coords(models.Model):
    latitude = models.FloatField()
    longitude = models.FloatField()

testTech/worldMap/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Coords
from django.http import JsonResponse
import json
import os


# Home view with the map. The only view disponible
def home(request):
    # We save the coodinates data from DB in the variable markers
    markers = Coords.objects.all()
    # We put them in context and name them markers
    context = {'markers': markers}
    # We render the HTML page and we can access to the data with the word 'markers' thanks to context in parameters
    return render(request, 'worldMap/testD3.html', context)

def getJson(request):
    THIS_FOLDER = os.path.dirname(os.path.abspath(__file__))
    my_file = os.path.join(THIS_FOLDER, 'templates/worldMap/departments.json')
    data = open(my_file).read()
    json_data = json.loads(data)

    return JsonResponse(json_data, safe=False)

testTech/worldMap/templates/worldMap/home.html
<!--
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
        <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>
    </head>
    <style>
        html, body { height: 100% }
    </style>

    <body onload="initialize()">
        <div id="map" style="width:100%; height:100%"></div>
    </body>
</html>
<script type="text/javascript">

  /* Function which create the map */
    function initialize() {
        var map = L.map('map').setView([48.833, 2.333], 7); // LIGNE 18

        var OpenStreetMap_Mapnik = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
	         maxZoom: 19,
	          attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
          });

        map.addLayer(OpenStreetMap_Mapnik);

        /* Add the markers from the DataBase */

        {% for mark in markers %}
            L.marker([ {{mark.latitude}} , {{mark.longitude}} ]).addTo(map).bindPopup('Latitude: '+{{mark.latitude}}+' longitude: '+{{mark.longitude}});
        {% endfor %}
    }
</script> -->

testTech/worldMap/templates/worldMap/testD3.html
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <script src="https://d3js.org/d3.v5.js"></script>
        <style type="text/css">
          div.tooltip {
            position: absolute;
            text-align: center;
            color: black;
            width: 275px;
            height: 37px;
            padding: 2px;
            font: 12px sans-serif;
            background: grey;
            border: 0px;
            border-radius: 8px;
            pointer-events: none;
          }
        </style>
    </head>

    <body>
        <div id="map"></div>
    </body>
</html>

<script type="text/javascript">

    var div = d3.select("body").append("div")
    .attr("class", "tooltip")
    .style("opacity", 0);

    const width = document.getElementById("map").offsetWidth * 0.95,
    height = 600,
    legendCellSize = 20,
    colors = ['#d4eac7', '#c6e3b5', '#b7dda2', '#a9d68f', '#9bcf7d', '#8cc86a', '#7ec157', '#77be4e', '#70ba45', '#65a83e', '#599537', '#4e8230', '#437029', '#385d22', '#2d4a1c', '#223815'];

    const svg = d3.select('#map').append("svg")
        .attr("id", "svg")
        .attr("width", width)
        .attr("height", height)
        .attr("class", "svg");
    const projection = d3.geoNaturalEarth1()
    .scale(1)
    .translate([0, 0]);

    const path = d3.geoPath()
        .pointRadius(2)
        .projection(projection);

    const cGroup = svg.append("g");



    d3.json("{% url "worldMap:api" %}").then(function(geojson) {

        var b  = path.bounds(geojson),
            s = .99 / Math.max((b[1][0] - b[0][0]) / width, (b[1][1] - b[0][1]) / height),
            t = [(width - s * (b[1][0] + b[0][0])) / 2, (height - s * (b[1][1] + b[0][1])) / 2];

        projection
            .scale(s)
            .translate(t);

        // Création de la carte
        cGroup.selectAll("path")
            .data(geojson.features)
            .enter()
            .append("path")
            .attr("d", path)
            .attr("id", d => "code" + d.id)
            .attr("class", "country");


        // On récupère les 4 points contenus dans la BDD que l'on stocke dans la variable "marks"
        var marks = [];
        {% for mark in markers %}
          marks.push({long: {{mark.longitude}}, lat: {{mark.latitude}} })
        {% endfor %}

        // On ajoute les markers sur la map
        cGroup.selectAll(".mark")
            .data(marks)
            .enter()
            .append("svg:image")
            .attr('width', 20)
            .attr('height', 25)
            .attr("xlink:href",'https://cdn3.iconfinder.com/data/icons/softwaredemo/PNG/24x24/DrawingPin1_Blue.png')
            .attr("transform", function(d) {
              if (d.long > 0) {
                if (d.lat > 0){
                  return "translate(" + projection([d.long*0.98,d.lat*1.05]) + ")";
                }else{
                  return "translate(" + projection([d.long*0.98,d.lat*0.88]) + ")";
                }
              }else{
                if (d.lat > 0){
                  return "translate(" + projection([d.long*1.1,d.lat*1.05]) + ")";
                }else{
                  return "translate(" + projection([d.long*1.1,d.lat*0.88]) + ")";
                }
              }
              })
            .on("mouseover", function(d) {
            div.transition()
                .duration(200)
                .style("opacity", .9);
            div.html("Latitude : " + d.lat + "<br/>"
                  +  "Longitude : " + d.long)
                .style("left", (d3.event.pageX + 30) + "px")
                .style("top", (d3.event.pageY - 30) + "px")
            })
            .on("mouseout", function(d) {
                div.style("opacity", 0);
                div.html("")
                    .style("left", "-500px")
                    .style("top", "-500px");
            });

    });

</script>